#!/usr/bin/env python3


__Author__  = 'Alexis Rodriguez aka BinexisHATT'
__Collaborator__ = 'Kenny Masuda'
__Start__ = 2020_03_07
__End__ = 2020_03
__Version__ = '1.0'
__Email__ = 'rodriguez10011999@gmail.com'



try:
	import scanit
	import fileformat
	import hashlib
	import os
	import json
	import parser
	import interface
	from sys import exit
	from time import sleep
	from colored import fg, bg, attr
except ImportError as err:
	print(f'Import Error: {err}')



def singleScan(filename, apikey, fileformat, outfile=None):
	"""
	Sends and scans file using VirusTotal's API

		:parameters:

			filename (str) : name of file to scan
			apikey (str) : valid VirusTotal API key
			fileformat (str) : type of format to store the report generated by VirusTotal
			outfile (str) : name of file to create if options to create file was provided,
											default = None

		:returns:

			none
	"""

	# the contents of the file in bytes
	content = open(filename, 'rb').read()

	# the file generated based on the contents of the file
	file_hash = genSha256(content)

	# send file to get scanned
	scanit.sendFile(apikey, filename)

	# notify of wait time
	print('%s\nPlease wait patiently for your results ...\n%s' % (fg(154), attr(0)))
	sleep(2)

	# retrieve the files report
	result = scanit.getReport(file_hash)

	# check if the user wanted the results
	# to be saved as a CSV file
	if fileformat == 'csv':
		forCsv(result, outfile)

	# check if the user wanted the results
	# to be saved as a jSON file
	elif fileformat == 'json':
		forJson(result, outfile)

	# check if the user wanted the results
	# to be saved as a normal text file
	elif fileformat == 'norm':
		forNorm(result, outfile)

	# if the user did not specify a fileformat option
	# print the raw data as json to the console
	else:
		toConsole(result)



def masScan(filename, apikey, fileformat, outfile=None):
	"""
	Sends and scans multiple files (max is 50) using VirusTotal's API

		:parameters:

			filename (str) : name of file containing a list of files to scan
			apikey (str) : valid VirusTotal API key
			fileformat (str) : type of format to store the report generated by VirusTotal
			outfile (str) : name of file to create if options to create file was provided,
											default = None

		:returns:

			none
	"""

	# contains list of results for each
	# file that was scanned
	all_results = []
	# open file containing files to scan
	with open(filename, 'r') as allfiles:

		# notify of wait time
		print('%s\nPlease wait patiently for your results ...\n%s' % (fg(154), attr(0)))
		sleep(2)

		# this list will contain the data
		# from each scan and will be appended
		# to the all_results list
		result = []
		# loop through each file and perform
		# a scan on each one
		for file in allfiles:
			# read the files contents in bytes
			content = open(file, 'rb').read()

			# get the sha256 hash for the file
			file_hash = genSha256(content)

			# send the file to get scanned
			scanit.sendFile(apikey, filename)

			# retrieve scan report
			result = scanit.getReport(file_hash)

			# append results from the scans to the all_results list
			# to format the data with respect to the format
			# the user specified
			all_results.append(result)

		# check if the user wanted the results
		# to be saved as a CSV file
		if fileformat == 'csv':
			forCsv(all_results, outfile)

		# check if the user wanted the results
		# to be saved as a jSON file
		elif fileformat == 'json':
			forJson(all_results, outfile)

		# check if the user wanted the results
		# to be saved as a normal text file
		elif fileformat == 'norm':
			forNorm(all_results, outfile)

		# if the user did not specify a fileformat option
		# print the raw data as json to the console
		else:
			toConsole(all_results)



def forCsv(data, outfile):
	"""
	Converts the data received from VirusTotal into list containing desired elements
	to send to fileformat.toCsv for writing to CSV file.

		:parameters:

			data (dictionary) : report received for a particualr file
			outfile (str) : name of file to create if options to create file was provided

		:returns:

			none
	"""

	pass



def forJson(data, outfile):
	"""
	Converts the data received from VirusTotral into a json object to send
	to fileformat.toJson for writing comprehensible json data to a json file

		:parameters:

			data (dictionary) : report received for a particualr file
			outfile (str) : name of file to create if options to create file was provided

		:returns:

			none
	"""

	# load data as JSON text
	json_str = json.loads(data)

	# invoke function to store data into
	# JSON file
	fileformat.toJson(json_str)



def forNorm(data, outfile):
	"""
	Converts the data received from VirusTotral file report into data
	that can be analyzed to send to fileformat.toNorm for writing to a
	normal text file.

		:parameters:

			data (dictionary) : report received for a particualr file
			outfile (str) : name of file to create if options to create file was provided

		:returns:

			none
	"""

	pass




def toConsole(data):
	"""
	Displays raw data retrieve from VirusTotal's file report

		:parameters:

			data (dictionary) : report received for a particualr file

		:returns:

			none
	"""

	# load data as JSON text
	json_str = json.loads(data)

	print(json_str['data']['attributes']['last_analysis_stats'])



def genSha256(file_content):
	"""
	Generates SHA256 hash of a specific files contents

		:parameters:

			file_content (str) : all the contents the file as a string

		:returns:

			SHA256 hash of files content
	"""

	# generating sha256 hash and returning it
	return hashlib.sha256(file_content).hexdigest()




def programName():
	print('''
██╗   ██╗███████╗ ██████╗ █████╗ ███╗   ██╗    ██╗   ██╗ ██╗    ██████╗
██║   ██║██╔════╝██╔════╝██╔══██╗████╗  ██║    ██║   ██║███║   ██╔═████╗
██║   ██║███████╗██║     ███████║██╔██╗ ██║    ██║   ██║╚██║   ██║██╔██║
╚██╗ ██╔╝╚════██║██║     ██╔══██║██║╚██╗██║    ╚██╗ ██╔╝ ██║   ████╔╝██║
 ╚████╔╝ ███████║╚██████╗██║  ██║██║ ╚████║     ╚████╔╝  ██║██╗╚██████╔╝
  ╚═══╝  ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝      ╚═══╝   ╚═╝╚═╝ ╚═════╝
''')



def main():

	# get arguments
	arguments = parser.parseArgs()

	# dict containing values of arguments passed
	args_dict = {
		'single_file': arguments.single_file,
		'mass_file':   arguments.mass_file,
		'csv':         arguments.csv,
		'json':        arguments.csv,
		'norm':        arguments.norm,
		'output_file': arguments.output_file,
		'apikey':      arguments.apikey,
		'interface':   arguments.interface
  }

	if args_dict['interface']:
		interface.interface()

	else:
		# if no file format is passed, this variable will not change
		fileformat = None
		# # if file format is csv
		if args_dict['csv']:
			fileformat = 'csv'
		# if file format is json
		elif args_dict['json']:
			fileformat = 'json'
		# if fileformat is normal
		elif args_dict['norm']:
			fileformat = 'norm'

	if fileformat == None:
		if args_dict['single_file']:
			singleScan(
				args_dict['single_file'], # function arguments
				args_dict['apikey'],
				fileformat)

		 # if the m argument was given
		else:
			masScan(
				args_dict['mass_scan'], # function arguments
				args_dict['apikey'],
				fileformat)

	else:
		if args_dict['single_file']:
			singleScan(
				args_dict['single_file'], # function arguments
				args_dict['apikey'],
				fileformat,
				args_dict['output_file'])

		# if the m argument was given
		else:
			masScan(
				args_dict['mass_scan'], # function arguments 
				args_dict['apikey'],
				fileformat,
				args_dict['output_file'])



# begin the program
if __name__ == '__main__':
	try:
		main()
	# handle keyboard interrupt (ctrl+?)
	except KeyboardInterrupt:
		try:
			print('\n[-] %s%sProgram interrupted!%s' % (fg(233), bg(9), attr(0)))
			exit(0)
		except SystemExit:
			os._exit(0)

